jobs:
- name: Create-Tenant
  plan:
  - get: pipeline-git
  - get: acltoolkit-img
  - task: create-tenant
    image: acltoolkit-img
    config:
      platform: linux
      inputs:
      - name: pipeline-git
      run:
        path: pipeline-git/tasks/hello.sh
    params:
      APIC_LOGIN: {{apic_login}}
      APIC_PASSWORD: {{apic_password}}
      APIC_URL: {{apic_url}}

resources:
- name: acltoolkit-img
  type: docker-image
  source:
    repository: dockercisco/acitoolkit

- name: pipeline-git
  type: git
  source:
    uri: git@github.com:clijockey/pipeline-aci.git
    branch: master
    private_key: {{github_ssh_key}}