jobs:
- name: Create-Tenant
  plan:
  - get: git-pipeline-aci
    trigger: true
  - get: acltoolkit-img
  - task: create-tenant
    image: acltoolkit-img
    config:
      platform: linux
      inputs:
      - name: git-pipeline-aci
      run:
        path: git-pipeline-aci/tasks/hello.sh
    params:
      APIC_LOGIN: {{apic_login}}
      APIC_PASSWORD: {{apic_password}}
      APIC_URL: {{apic_url}}

- name: Create-Something
  plan:
  - get: git-pipeline-aci
    trigger: true
  - get: acltoolkit-img
  - task: create-tenant
    image: acltoolkit-img
    config:
      platform: linux
      inputs:
      - name: git-pipeline-aci
      run:
        path: git-pipeline-aci/tasks/aci-create-tenant.py -u {{apic_url}} -l {{apic_login}} -p {{apic_password}} -t "something"

resources:
- name: acltoolkit-img
  type: docker-image
  source:
    repository: dockercisco/acitoolkit

- name: git-pipeline-aci
  type: git
  source:
    uri: git@github.com:clijockey/pipeline-aci.git
    branch: master
    private_key: {{github_ssh_key}}