jobs:
- name: Configure-ACI
  plan:
  - get: git-pipeline-aci
    trigger: true
  - get: acltoolkit-img
  - task: create-tenant
    image: acltoolkit-img
    config:
      platform: linux
      inputs:
      - name: git-pipeline-aci
      run:
        path: sh
        args:
        - -exc # Once live remove the -x flag :-)
        - |
          echo "Create Tenant"

          APIC_LOGIN={{apic_login}} \
          APIC_PASSWORD={{apic_password}} \
          APIC_URL={{apic_url}} \
          git-pipeline-aci/tasks/aci-create-tenant.py -t test
  - task: create-bd
    image: acltoolkit-img
    config:
      platform: linux
      inputs:
      - name: git-pipeline-aci
      run:
        path: sh
        args:
        - -exc
        - |
          echo "Create Bridge Domain"

          # APIC_LOGIN={{apic_login}} \
          # APIC_PASSWORD={{apic_password}} \
          # APIC_URL={{apic_url}} \
          # git-pipeline-aci/tasks/aci-create-bd.py

          # --tenant TENANT       The name of Tenant
          # --vrf VRF             The name of VRF
          # --bd BD               The name of BridgeDomain
          # --address ADDRESS     Subnet IPv4 Address
          # --scope SCOPE         The scope of subnet ("public", "private", "shared",
          #                       "public,shared", "private,shared", "shared,public",
          #                       "shared,private")
          # --json [JSON]         Json output only

resources:
- name: acltoolkit-img
  type: docker-image
  source:
    repository: dockercisco/acitoolkit

- name: git-pipeline-aci
  type: git
  source:
    uri: git@github.com:clijockey/pipeline-aci.git
    branch: master
    private_key: {{github_ssh_key}}